export enum UserRole {
  ADMIN = 'ADMIN',
  BUYER = 'BUYER',
  CARSHOWROOM_ADMIN = 'CARSHOWROOM_ADMIN',
  CARSHOWROOM_MANAGER = 'CARSHOWROOM_MANAGER',
  CARSHOWROOM_AUTOMECHANIC = 'CARSHOWROOM_AUTOMECHANIC',
  CARSHOWROOM_SALES = 'CARSHOWROOM_SALES',
  CARSHOWROOM_SERVICE_MANAGER = 'CARSHOWROOM_SERVICE_MANAGER',
  MANAGER = 'MANAGER',
  SELLER = 'SELLER',
  SELLER_PREMIUM = 'SELLER_PREMIUM',
}
